import { makeStyles } from "@material-ui/core";

export const useStyles = makeStyles({
  container: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    margin: "1rem",
  },
  smallContainer: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    backgroundImage: "linear-gradient(#c9d2f3, #c9e7f3)",
    margin: "1rem",
    border: "0.1rem solid #c9e7f3",
    borderRadius: "0.2rem",
  },
  navContainer: {
    margin: "0rem 0.2rem 0rem 0.2rem",
    backgroundImage: "linear-gradient(#c9e7f3, #c9d2f3)",
    border: "0.1rem solid #c9e7f3",
    borderRadius: "0.2rem",
    paddingBottom: "1rem",
    zIndex: "10",
  },
  menuContainer: {
    margin: "0.5rem",
    backgroundImage: "linear-gradient(#c9e7f3, #c9d2f3)",
    border: "0.1rem solid #c9e7f3",
    borderRadius: "0.2rem",
  },
  subContainer: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    padding: "0.5rem",
  },
  flexContainer: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  paper: {
    backgroundColor: "#c9e7f3",
    margin: "1rem",
    textAlign: "left",
    padding: "1rem 1rem 1rem 0.5rem",
  },
  paperText: {
    fontFamily: "Roboto Condensed",
    marginLeft: "2rem",
    marginBottom: "1rem",
  },
  justifyText: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  overlined: {
    borderTop: "0.1rem dotted #080c26",
    borderBottom: "0.1rem dotted #080c26",
  },
  icon: {
    width: "10%",
    height: "auto",
    margin: 0,
    paddingRight: "0.5rem",
  },
  headingText: {
    fontFamily: "Fascinate Inline",
  },
  subheadingText: {
    marginTop: "1rem",
    fontFamily: "Fascinate Inline",
  },
  text: {
    fontFamily: "Roboto Condensed",
  },
  marginText: {
    marginRight: '0.2rem',
    fontFamily: "Roboto Condensed",
  },
  inlineList: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
  },
  menuList: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  menuLink: {
    margin: "0.2rem",
  },
  smallCard: {
    marginTop: "0.5rem",
    marginBottom: "0.5rem",
    width: "80%",
    boxShadow: "0.5rem 0.2rem 0.2rem #c9d2f3",
    borderRadius: "0.2rem",
  },
  extraSmallCard: {
    margin: "0.5rem",
    width: 200,
    height: 175,
    boxShadow: "0.5rem 0.2rem 0.2rem #c9d2f3",
    borderRadius: "0.2rem",
    justifyContent: "center",
    textAlign: "center",
    alignItems: "center",
  },
  alignButton: {
    justifyContent: "center",
    textAlign: "center",
    alignItems: "center",
  },
  cardButton: {
    fontFamily: "Roboto Condensed",
    border: "0.1rem solid #c9e7f3",
    borderRadius: "0.2rem",
    backgroundColor: "#c9e7f3",
  },
  card: {
    height: 500,
    width: 400,
    margin: "0.5rem",
    boxShadow: "0.5rem 0.2rem 0.2rem #c9d2f3",
    borderRadius: "0.2rem",
    justifyContent: "center",
    textAlign: "center",
    alignItems: "center",
  },
  cardImg: {
    height: 0,
    paddingTop: "56.25%", // 16:9,
    marginTop: "30",
  },
  leftBox: {
    fontFamily: "Roboto Condensed",
    border: "0.1rem solid #c9e7f3",
    borderRadius: "0.2rem",
    backgroundColor: "#c9e7f3",
    textAlign: "center",
    marginTop: "1rem",
    width: "50%",
  },
  input: {
    width: "50%",
    margin: "0.2rem",
    fontFamily: "Roboto Condensed",
  },
  select: {
    width: "50%",
  },
  smallAlert: {
    width: "50%",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  unstaticFooter: {
    height: "4rem",
    margin: "1rem",
    backgroundImage: "linear-gradient(#c9d2f3, #c9e7f3)",
    border: "0.1rem solid #c9e7f3",
    borderRadius: "0.2rem",
    padding: "0.2rem",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  bigButton: {
    width: "50%",
    margin: "0.2rem",
  },
  accordion: {
    margin: '0.2rem',
  },
  bigCard: {
    height: 'auto',
    width: '100%',
    margin: "0.2rem",
    boxShadow: "0.5rem 0.2rem 0.2rem #c9d2f3",
    borderRadius: "0.2rem",
    justifyContent: "center",
    textAlign: "center",
    alignItems: "center",
  },
  bigcardImg: {
    margin: '0.2rem',
    borderRadius: "0.2rem",
  },
  cardAvatar: {
    height: 100,
  },
});
